[package]
name = "sex"
description = "Sample Explorer"
version = "0.1.0"
edition = "2021"

# Example of usage: cargo build --profile=release-with-debug
[profile.release-with-debug]
inherits = "release"
debug = true

[dependencies]
apodize = "1.0.0"
async-std = "1.12.0"
fern = "0.7.1"
file_icon_provider = "0.4.0"
humantime = "2.2.0"
iced = { git = "https://github.com/iced-rs/iced", rev = "beddf49c76f3b43e7b33452831e1293cad28fd89", features = ["async-std", "svg", "image", "canvas"] }
itertools = "0.14.0"
log = "0.4.26"
mime = "0.3.17"
mime_guess = "2.0.5"
notify = "8.0.0"
rfd = "0.15.0"
rodio = { git = "https://github.com/RustAudio/rodio", rev = "1671d361536a54e4931434e199df3a1ff03663c8" }
rustfft = "6.2.0"
thiserror = "2.0.12"

[dev-dependencies]
rstest = "0.24.0"
