[package]
name = "sex"
description = "Sample Explorer"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.12.0"
iced = { git = "https://github.com/iced-rs/iced.git", features = ["async-std", "svg"] }
mime = "0.3.17"
mime_guess = "2.0.5"
rfd = "0.14.1"
rodio = "0.19.0"
