[package]
name = "sex"
description = "Sample Explorer"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.12.0"
file_icon_provider = "0.3.1"
iced = { git = "https://github.com/IohannRabeson/iced", features = ["async-std", "svg", "image", "canvas"] }
mime = "0.3.17"
mime_guess = "2.0.5"
rfd = "0.15.0"
rodio = { git = "https://github.com/RustAudio/rodio" }
