name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: rustup toolchain install stable --profile minimal
    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y libasound2-dev libgtk-4-dev libgtk-3-dev libatk1.0-dev
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.8
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
