name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: rustup toolchain install stable --profile minimal
    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libasound2-dev libgtk-4-dev libgtk-3-dev libatk1.0-dev
        version: 1.0
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.8
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
